title: Nathan Dela Paz
description: Nathan Dela Paz's personal website
theme: just-the-docs

url: https://just-the-docs.github.io

# Aux links for the upper right navigation
aux_links:
  "Github":
    - "https://github.com/njdelapaz/"
  "LinkedIn":
    - "https://www.linkedin.com/in/nathandelapaz/"

search_enabled: false
